name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          base: header
          plugin_languages: yes
          plugin_licenses: yes
          plugin_activity: yes
          config_timezone: Asia/Colombo
          token: ${{ secrets.METRICS_TOKEN }}